import { ReleaseResponseSchema } from '@openmaintainer/ai';
import {
  type ReleaseNotesInput,
  type ReleaseNotesResult,
  sanitizeMarkdown,
  truncate,
} from '@openmaintainer/shared';
import type { AIProvider } from '@openmaintainer/ai';
import type { OpenMaintainerConfig } from '@openmaintainer/config';
export class ReleaseNotesService {
  constructor(
    private readonly provider: AIProvider,
    private readonly config: OpenMaintainerConfig,
  ) {}
  async generate(input: ReleaseNotesInput): Promise<ReleaseNotesResult> {
    if (!this.config.releaseNotes.enabled) {
      return {
        markdown: `## Changes from ${sanitizeMarkdown(input.from)} to ${sanitizeMarkdown(input.to)}\n\nRelease-note generation is disabled by configuration.`,
        changes: [],
      };
    }
    if (input.pullRequests.length > 200)
      throw new Error('Release notes accept at most 200 pull requests; split the range.');
    const raw = ReleaseResponseSchema.parse(
      await this.provider.generateReleaseNotes({
        ...input,
        pullRequests: input.pullRequests.map((pr) => ({
          ...pr,
          title: pr.title.slice(0, 500),
          body: pr.body.slice(0, 2000),
          labels: pr.labels.slice(0, 20).map((label) => label.slice(0, 50)),
        })),
      }),
    );
    const byReference = new Map(input.pullRequests.map((pr) => [`#${pr.number}`, pr]));
    const allowed = new Set([
      'Added',
      'Changed',
      'Fixed',
      'Performance',
      'Security',
      'Documentation',
      'Dependencies',
      'Other',
    ]);
    const changes = raw
      .filter(
        (change, index, all) =>
          byReference.has(change.reference) &&
          all.findIndex((c) => c.reference === change.reference) === index,
      )
      .map((change) => ({
        ...change,
        category: change.category,
        text: sanitizeMarkdown(truncate(byReference.get(change.reference)!.title, 500)),
        reference: change.reference,
      }));
    const groups = new Map<string, typeof changes>();
    for (const change of changes)
      groups.set(change.category, [...(groups.get(change.category) ?? []), change]);
    const lines = [
      `# Release notes: ${sanitizeMarkdown(input.from)} → ${sanitizeMarkdown(input.to)}`,
      '',
    ];
    for (const category of allowed) {
      const items = groups.get(category) ?? [];
      if (items.length) {
        lines.push(`## ${category}`);
        for (const item of items) {
          const url = byReference.get(item.reference)?.url;
          lines.push(`- ${item.text} (${item.reference})${url ? ` — ${url}` : ''}`);
        }
        lines.push('');
      }
    }
    lines.push('_Generated by OpenMaintainer from traceable pull request metadata._');
    return { markdown: lines.join('\n'), changes };
  }
}
