import type { AIProvider } from '@openmaintainer/ai';
import type { OpenMaintainerConfig } from '@openmaintainer/config';
import {
  type DuplicateCandidate,
  type DuplicateIssueInput,
  type DuplicateComparison,
  type IssueTriageInput,
  type IssueTriageResult,
  type PullRequestFile,
  type PullRequestReviewInput,
  type PullRequestReviewResult,
  type ReleaseNotesInput,
  type ReleaseNotesResult,
  type ReviewFinding,
  type Risk,
} from '@openmaintainer/shared';
import { jaccardSimilarity, marker, sanitizeMarkdown, truncate } from '@openmaintainer/shared';

export const BOT_FOOTER =
  '— Generated by OpenMaintainer. AI-assisted analysis may be imperfect; maintainer judgment takes precedence.';
function isIgnored(path: string, patterns: string[]): boolean {
  return patterns.some((pattern) => {
    const normalized = pattern
      .replace(/^\*\*\//, '')
      .replace(/\*\*/g, '.*')
      .replace(/\*/g, '[^/]*')
      .replace(/\./g, '\\.');
    try {
      return new RegExp(`^${normalized}$`).test(path) || new RegExp(`${normalized}$`).test(path);
    } catch {
      return false;
    }
  });
}
function priority(file: PullRequestFile): number {
  const path = file.path.toLowerCase();
  if (
    /auth|security|middleware|permission|crypto|migration|workflow|dockerfile|package\.json/.test(
      path,
    )
  )
    return 0;
  if (file.binary) return 90;
  if (/lock|dist|build|coverage|vendor|min\.js/.test(path)) return 100;
  if (/test|spec/.test(path)) return 30;
  if (/\.(ts|tsx|js|jsx|py|go|rs|java|rb|php|c|cpp)$/.test(path)) return 10;
  if (/ya?ml|json|toml/.test(path)) return 20;
  return 40;
}
export function prioritizeFiles(
  files: PullRequestFile[],
  maxFiles: number,
  ignore: string[],
): { files: PullRequestFile[]; skipped: string[] } {
  const eligible = files.filter((file) => !file.binary && !isIgnored(file.path, ignore));
  const selected = [...eligible]
    .sort((a, b) => priority(a) - priority(b) || a.path.localeCompare(b.path))
    .slice(0, maxFiles);
  const selectedPaths = new Set(selected.map((file) => file.path));
  return {
    files: selected,
    skipped: files.filter((file) => !selectedPaths.has(file.path)).map((file) => file.path),
  };
}
export function calculateRisk(input: {
  files: PullRequestFile[];
  findings: ReviewFinding[];
  partial?: boolean;
}): Risk {
  const sensitive = input.files.some((f) =>
    /auth|security|crypto|permission|migration|\.github\/workflows|dockerfile|package\.json/i.test(
      f.path,
    ),
  );
  const score = input.files.length > 20 ? 1 : 0;
  const findingScore = input.findings.some(
    (f) => f.severity === 'critical' || f.severity === 'high',
  )
    ? 2
    : input.findings.some((f) => f.severity === 'medium')
      ? 1
      : 0;
  const total = score + (sensitive ? 1 : 0) + findingScore + (input.partial ? 1 : 0);
  return total >= 3 ? 'high' : total >= 1 ? 'medium' : 'low';
}
export class ReviewService {
  constructor(
    private readonly provider: AIProvider,
    private readonly config: OpenMaintainerConfig,
  ) {}
  async review(input: PullRequestReviewInput): Promise<PullRequestReviewResult> {
    if (!this.config.review.enabled)
      return {
        summary: 'Pull request review is disabled by configuration.',
        findings: [],
        testing: '',
        risk: 'low',
        partial: false,
        analyzedFiles: 0,
        skippedFiles: [],
      };
    const chosen = prioritizeFiles(
      input.files,
      this.config.review.maxFiles,
      this.config.review.ignore,
    );
    const maxChars = this.config.review.maxDiffCharacters;
    let used = 0;
    const bounded = chosen.files
      .map((file) => {
        const patch = file.patch ?? '';
        const remaining = maxChars - used;
        if (remaining <= 0) return { ...file, patch: '' };
        const next = patch.slice(0, remaining);
        used += next.length;
        return { ...file, patch: next };
      })
      .filter((file) => file.patch !== '');
    const partial = chosen.skipped.length > 0 || bounded.length < chosen.files.length;
    const providerResult = await this.provider.reviewPullRequest({ ...input, files: bounded });
    const findings = providerResult.findings
      .filter((finding) => finding.confidence >= this.config.review.minimumConfidence)
      .slice(0, this.config.review.maxInlineComments);
    return {
      summary: sanitizeMarkdown(truncate(providerResult.summary, 2000)),
      findings: findings.map((finding) => ({
        ...finding,
        title: sanitizeMarkdown(finding.title),
        explanation: sanitizeMarkdown(finding.explanation),
        recommendation: sanitizeMarkdown(finding.recommendation),
      })),
      testing: sanitizeMarkdown(truncate(providerResult.testing, 1500)),
      risk: calculateRisk({ files: bounded, findings, partial }),
      partial,
      analyzedFiles: bounded.length,
      skippedFiles: chosen.skipped,
    };
  }
}
export function renderReviewComment(result: PullRequestReviewResult): string {
  const findings = result.findings.length
    ? result.findings
        .map(
          (f, i) =>
            `${i + 1}. **${f.severity} / ${f.category} — ${f.title}**${f.line ? ` ([${f.file}:${f.line}])` : ` (${f.file})`}\n   ${f.explanation}\n   **Recommendation:** ${f.recommendation}`,
        )
        .join('\n\n')
    : 'No high-confidence actionable issues were identified.';
  const partial = result.partial
    ? `\n\n> Partial analysis: ${result.analyzedFiles} file(s) were analyzed. Skipped or truncated paths: ${result.skippedFiles.slice(0, 20).join(', ') || 'diff size limit'}.`
    : '';
  return `${marker('pr-review')}\n## OpenMaintainer Review\n\n### Summary\n${result.summary}\n\n### Risk\n**${result.risk.charAt(0).toUpperCase()}${result.risk.slice(1)}**\n\n### Findings (${result.findings.length})\n${findings}\n\n### Testing\n${result.testing || 'No testing information was returned.'}${partial}\n\n${BOT_FOOTER}`;
}

export class IssueTriageService {
  constructor(
    private readonly provider: AIProvider,
    private readonly config: OpenMaintainerConfig,
  ) {}
  async triage(input: IssueTriageInput): Promise<IssueTriageResult> {
    if (!this.config.issues.enabled || !this.config.issues.triage.enabled)
      return {
        category: 'other',
        summary: 'Issue triage is disabled by configuration.',
        suggestedLabels: [],
        missingInformation: [],
        isSecuritySensitive: false,
        possibleDuplicate: false,
      };
    const result = await this.provider.triageIssue(input);
    return {
      ...result,
      summary: sanitizeMarkdown(truncate(result.summary, 1000)),
      suggestedLabels: result.suggestedLabels
        .map((label) => label.replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 50))
        .filter(Boolean),
      missingInformation: result.missingInformation.map((item) =>
        sanitizeMarkdown(item).slice(0, 200),
      ),
    };
  }
}
export function renderTriageComment(result: IssueTriageResult): string {
  const security = result.isSecuritySensitive
    ? "\n\n> This may contain security-sensitive information. Please use the repository's private security disclosure channel rather than sharing exploit details publicly."
    : '';
  const missing = result.missingInformation.length
    ? `\n\n**Helpful missing information:** ${result.missingInformation.join(', ')}.`
    : '';
  return `${marker('issue-triage')}\n## OpenMaintainer Triage\n\n**Category:** ${result.category}\n\n${result.summary}\n\n**Suggested labels:** ${result.suggestedLabels.length ? result.suggestedLabels.map((label) => `\`${label}\``).join(', ') : 'None'}${missing}${security}\n\n${BOT_FOOTER}`;
}

export class DuplicateService {
  constructor(
    private readonly provider: AIProvider,
    private readonly config: OpenMaintainerConfig,
  ) {}
  async find(
    issue: IssueTriageInput,
    candidates: DuplicateCandidate[],
  ): Promise<DuplicateComparison[]> {
    if (!this.config.issues.enabled || !this.config.issues.duplicates.enabled) return [];
    const ranked = candidates
      .filter((candidate) => candidate.number !== issue.number)
      .map((candidate) => ({
        ...candidate,
        similarity: jaccardSimilarity(
          `${issue.title} ${issue.body}`,
          `${candidate.title} ${candidate.body}`,
        ),
      }))
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, this.config.issues.duplicates.maxCandidates);
    if (!ranked.length) return [];
    const comparisons = await this.provider.compareDuplicateIssues({
      issue,
      candidates: ranked,
    } satisfies DuplicateIssueInput);
    return comparisons
      .filter(
        (comparison) => comparison.confidence >= this.config.issues.duplicates.minimumConfidence,
      )
      .sort((a, b) => b.confidence - a.confidence);
  }
}
export function renderDuplicateComment(
  results: DuplicateComparison[],
  candidates: DuplicateCandidate[],
): string {
  const links = results
    .map((result) => {
      const candidate = candidates.find((item) => item.number === result.number);
      return `- Possible duplicate: ${candidate?.url ?? `#${result.number}`} (${Math.round(result.confidence * 100)}% confidence) — ${sanitizeMarkdown(result.reason)}`;
    })
    .join('\n');
  return `${marker('duplicates')}\n## OpenMaintainer Duplicate Check\n\n${links || 'No high-confidence duplicate candidates were identified.'}\n\n${BOT_FOOTER}`;
}

export class ReleaseNotesService {
  constructor(
    private readonly provider: AIProvider,
    private readonly config: OpenMaintainerConfig,
  ) {}
  async generate(input: ReleaseNotesInput): Promise<ReleaseNotesResult> {
    if (!this.config.releaseNotes.enabled) {
      return {
        markdown: `## Changes from ${input.from} to ${input.to}\n\nRelease-note generation is disabled by configuration.`,
        changes: [],
      };
    }
    const raw = await this.provider.generateReleaseNotes(input);
    const byReference = new Map(input.pullRequests.map((pr) => [`#${pr.number}`, pr]));
    const allowed = new Set([
      'Added',
      'Changed',
      'Fixed',
      'Performance',
      'Security',
      'Documentation',
      'Dependencies',
      'Other',
    ]);
    const changes = raw
      .filter((change) => byReference.has(change.reference))
      .map((change) => ({
        ...change,
        category: allowed.has(change.category) ? change.category : 'Other',
        text: sanitizeMarkdown(truncate(change.text, 500)),
        reference: change.reference,
      }));
    const groups = new Map<string, typeof changes>();
    for (const change of changes)
      groups.set(change.category, [...(groups.get(change.category) ?? []), change]);
    const lines = [`# Release notes: ${input.from} → ${input.to}`, ''];
    for (const category of allowed) {
      const items = groups.get(category) ?? [];
      if (items.length) {
        lines.push(`## ${category}`);
        for (const item of items) {
          const url = byReference.get(item.reference)?.url;
          lines.push(`- ${item.text} (${item.reference})${url ? ` — ${url}` : ''}`);
        }
        lines.push('');
      }
    }
    lines.push('_Generated by OpenMaintainer from traceable pull request metadata._');
    return { markdown: lines.join('\n'), changes };
  }
}

export type Command = 'help' | 'review' | 'summarize' | 'triage' | 'duplicates' | 'release-notes';
export function parseCommand(body: string, prefix = '/om'): Command | undefined {
  const first = body.trim().split(/\s+/)[0];
  if (!first?.startsWith(`${prefix} `) && first !== prefix) return undefined;
  const command = body.trim().split(/\s+/)[1] as Command | undefined;
  return command &&
    ['help', 'review', 'summarize', 'triage', 'duplicates', 'release-notes'].includes(command)
    ? command
    : command === undefined
      ? 'help'
      : undefined;
}
export function canRunCommand(role: string | undefined, config: OpenMaintainerConfig): boolean {
  if (!config.commands.enabled) return false;
  return (
    role !== undefined &&
    config.commands.allowedRoles.includes(role as 'admin' | 'maintain' | 'write')
  );
}
export function commandHelp(prefix = '/om'): string {
  return `Available commands: ${prefix} help, ${prefix} review, ${prefix} summarize, ${prefix} triage, ${prefix} duplicates. Privileged commands require write, maintain, or admin repository access.`;
}
